apiVersion: v1
kind: Pod
metadata:
  name: "phpserver"
  labels:
    app: "phpserver"
spec:
  containers:
  - name: "phpserver"
    image: "farofapereira/kubernetes-hello-php"


# Aplicar arquivo de configuracao (rodar na raiz do projeto)
# kubectl apply -f k8s/pod.yml
# não é bom fazer isso, porque se der algum problema no pod, ele nao vai reiniciar sozinho, o melhor é deixar o 
#   kubernetes gerenciar isso

# Get all pods
# kubectl get pods

# Delete pod
# kubectl delete pod <pod_name>

# Port forward to pod
# kubectl port-forward pod/<pod_name> <port_local>:<port_container>
# eg.
# kubectl port-forward pod/phpserver 8005:8005