apiVersion: v1
kind: Secret
metadata:
  name: phpserver-secret
type: Opaque #If not defined, by default is opaque
data:
  #values should be in base64
  USER: "" 
  PASSWORD: ""

# to encode string
# echo "<string_to_be_encoded>" | base64 
#     É necessario atualizar o deployment para atualizar as variaveis
#     kubectl apply -f k8s/secret.yml 
#     kubectl apply -f k8s/deployment.yml  

# IMPORTANT
# secrets are environment variables, so aren't encrypted
#   if you echo the secret inside the pod you'll get the value
#   kubectl exec -it <pod_name> -- bash
#   echo $PASSWORD